package main

import (
	"fmt"

	"github.com/codahale/chacha20poly1305"
)

func readSecretKey(i int) []byte {
	return make([]byte, i)
}

func readRandomNonce(i int) []byte {
	return make([]byte, i)
}

func main() {

	key := readSecretKey(chacha20poly1305.KeySize) // must be 256 bits long
	key = []byte("a very very very very secret key")
	c, err := chacha20poly1305.New(key)
	fmt.Print(c)
	if err != nil {
		panic(err)
	}

	nonce := readRandomNonce(c.NonceSize()) // must be generated by crypto/rand
	fmt.Println(nonce)
	plaintext := []byte("wwz")
	data := []byte("whoah yeah")
	ciphertext := c.Seal(nil, nonce, plaintext, data)
	opentext, _ := c.Open(nil, nonce, ciphertext, data)

	fmt.Printf("%x\n", ciphertext)
	fmt.Printf("%s\n", opentext)
}
